### ISSUE TITLE
graphbasedslam8.ipynb：ランドマーク位置とMapEdgeの共分散行列の計算方法について

### ISSUE THREAD

**Issue by hotsuyuki** [ryuichiueda/LectureOfProbabilisticRobotics#4]
分かりやすい解説書を執筆頂きありがとうございます．大変勉強になります．
[graphbasedslam8.ipynb](https://github.com/ryuichiueda/LNPR_BOOK_CODES/blob/master/section_graph_slam/graphbasedslam8.ipynb)（書籍では9.4節）について2点質問があります．

## ①
セル11のランドマーク位置を推定する箇所の式が [graphbasedslam7.ipynb](https://github.com/ryuichiueda/LNPR_BOOK_CODES/blob/master/section_graph_slam/graphbasedslam7.ipynb) の時と変わらず平均位置の式になっておりますが，正しくは以下の式でしょうか？

```
ms[landmark_id] = np.mean([e.m for e in edges], axis=0)
```
↓ 
```
ms[landmark_id] = np.linalg.inv(Omega).dot(xi)
```

※ 第1刷の書籍に記載のソースコード（P. 234）では `ms` がリストで `append` していく形でしたが， `ms` は辞書のままの方が後の  `draw()` 関数に引数として渡しやすいかなと思いました．

## ②
セル10の `self.Omega`（書籍ではP. 233の式(9.65)）が精度行列ではなく共分散行列の式になっていると思いまして，正しくは以下の式かと思われますがいかがでしょうか？

```
self.Omega = R.dot(Q1).dot(R.T)
self.xi = self.Omega.dot(self.m)
```
↓ 
```
self.Sigma = R.dot(Q1).dot(R.T) ### Covariance matrix
self.Omega = np.linalg.inv(self.Sigma) ### Information matrix
self.xi = self.Omega.dot(self.m)
```

※ `MapEdge.Sigma = R * Q1 * R^T`，`MapEdge.Omega = MapEdge.Sigma^-1` とした場合の，最小二乗法の式を

* ②-a `Omega = sum(MapEdge.Sigma)`，`xi = sum(MapEdge.Sigma * MapEdge.m)`
* ②-b `Omega = sum(MapEdge.Omega)`，`xi = sum(MapEdge.Omega * MapEdge.m)`

として比較した出力結果を以下に添付します．
最も近くからランドマークを観測した観測エッジを緑線で描画しており，②-b の方が近くから観測した観測エッジに重きが置かれています．

②-a
<img width="656" alt="Screen Shot 2020-05-24 at 17 45 42" src="https://user-images.githubusercontent.com/26198619/82750109-f533af00-9de8-11ea-8a0d-32a8e8bb7d23.png">

②-b
<img width="656" alt="Screen Shot 2020-05-24 at 17 43 17" src="https://user-images.githubusercontent.com/26198619/82750160-2e6c1f00-9de9-11ea-9f6d-88fe924cb422.png">

**Comment by ryuichiueda** [comment]
大変ありがとうございます。

①は書籍では正しかったのですがリポジトリの内容が先祖返りしていました。コードのアドバイスありがとうございます。

②は式(9.65)がまちがっていてそのままコードにも反映していました。書籍の記述も少し直さないといけません。

修正して、ウェブサイトに掲載します。ありがとうございました。
