### ISSUE TITLE
12.4.4 動作確認 のaction_valueメソッドで未定義のdpを参照している 

### ISSUE THREAD

**Issue by shuhei23** [ryuichiueda/LectureOfProbabilisticRobotics#6]
下記の行の`dp.obs_sigma_transition_probs[(*after, sigma_after)].items()`で定義していない変数`dp`を参照しています。
正しくは`self.obs_sigma_transition_probs[(*after, sigma_after)].items()`だと思われます。
![image](https://github.com/ryuichiueda/LNPR_BOOK_CODES/assets/64341454/8c028281-1558-413a-8f07-8a79df389c4d)
https://github.com/ryuichiueda/LNPR_BOOK_CODES/blob/master/section_pomdp/amdp7.ipynb?short_path=1f51208#L135
テキストでは 12.4.4章および12.4.5章のコードの表示のところも同様と思われます．

**Comment by ryuichiueda** [comment]
ながらく放置してすみません！！確認します！！！

**Comment by ryuichiueda** [comment]
なおすはなおすとして、グローバルでdpというオブジェクトを作っているので、こいつを参照しているっぽいです。
（エラーが出てないのはそういうことかと）

**Comment by ryuichiueda** [comment]
コードを修正しました。正誤表 https://b.ueda.tech/?page=lnpr_typo にも記載しました。

ありがとうございました！
